accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('',  views.home, name="home"),
    path('login/', views.my_login_view, name="login"),
    path("verify/two-factor/", views.two_factor_view, name="two_factor"),
    path('log-out/', views.logout_view, name="logout_view"),
    path('generate_new_code/', views.generate_new_code, name="generate_new_code"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('accounts.urls', namespace="accounts")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
import random
import datetime
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.hashers import make_password
# Create your models here.

def generate_code():
    code = random.randint(100000, 999999)
    try:
        TwoFactorAuth.objects.get(code=code)
        return generate_code()
    except TwoFactorAuth.DoesNotExist:
        return code

class MyUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)

class MyUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)
    objects = MyUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []


class TwoFactorAuth(models.Model):
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE, related_name="user_two_factor")
    code = models.CharField(max_length=6)
    expires = models.DateTimeField(auto_now=True)
    verify = models.BooleanField(default=False)


    def save(self, update_fields=None, *args, **kwargs):
        if not self.code or update_fields:
            self.code = generate_code()
        super().save(*args, **kwargs)

    @property
    def check_expires_code(self):
        minutes_difference = datetime.datetime.now().minute - self.expires.minute
        return minutes_difference

accounts/forms.py
from typing import Any
from django import forms
from .models import TwoFactorAuth
from django.contrib.auth.forms import AuthenticationForm, UsernameField

class TwoFactorForm(forms.ModelForm):
    class Meta:
        model = TwoFactorAuth
        fields = ("code",)
        widgets = {
            'code': forms.TextInput(attrs={"class": "form-control mb-4"})
        }

class MyAuthenticationForm(AuthenticationForm):
    username = UsernameField(widget=forms.EmailInput(attrs={"autofocus": True}))

    def __init__(self, request: Any = ..., *args: Any, **kwargs: Any) -> None:
        super().__init__(request, *args, **kwargs)
        self.fields["username"].widget.attrs.update({"class": "form-control"})
        self.fields["password"].widget.attrs.update({"class": "form-control"})

accounts/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, get_user_model, logout
from .models import TwoFactorAuth
from .forms import TwoFactorForm, MyAuthenticationForm
from django.contrib.auth.decorators import login_required
from .decorators import two_factor_required
from django.contrib import messages
User = get_user_model()


def my_login_view(request):
    if request.method == "POST":
        form = MyAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            if user is not None:
                TwoFactorAuth.objects.get_or_create(user=user)
                send_mail(
                    "Kodi me 6 shifra i gjeruar",
                    f"kodi: {user.user_two_factor.code}.",
                    "from@example.com",
                    ["to@example.com"],
                    fail_silently=False,
                )
                login(request, user)
                return redirect("accounts:two_factor")
    else:
        form = MyAuthenticationForm()
    return render(request, 'login.html', {"form": form})


@login_required
@two_factor_required
def home(request):
    return render(request, 'home.html')


@login_required
def two_factor_view(request):
    expired = False
    get_twofactor = get_object_or_404(TwoFactorAuth, user_id=request.user.id)
    if request.method == "POST":
        form = TwoFactorForm(data=request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            if get_twofactor.code == code:
                if get_twofactor.check_expires_code < 2:
                    get_twofactor.verify = True
                    get_twofactor.save(update_fields=["verify"])
                    return redirect("accounts:home")
                else:
                    expired = True
                    messages.add_message(request, messages.WARNING, "Your code has expired, please request another one.", extra_tags="warning")
            else:
                messages.add_message(request, messages.ERROR, "The code you entered is incorrect.", extra_tags="danger")
    else:
        form = TwoFactorForm()
    return render(request, 'two_factor.html', {'form': form, "expired": expired})

@login_required
def generate_new_code(request):
    TwoFactorAuth.objects.update_or_create(user=request.user)
    send_mail(
        "Kodi me 6 shifra i gjeruar",
        f"kodi: {request.user.user_two_factor.code}.",
        "from@example.com",
        ["to@example.com"],
        fail_silently=False,
    )
    return redirect("accounts:two_factor")

@login_required
def logout_view(request):
    get_twofactor = get_object_or_404(TwoFactorAuth, user_id=request.user.id)
    get_twofactor.delete()
    logout(request)
    return redirect("accounts:login")

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="d-flex justify-content-center align-items-center min-vh-100 flex-column">
    {% block content %}
    {% endblock %}
    </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Hello, world!</h1>
<a href="{% url 'accounts:logout_view' %}">logout</a>
{% endblock %}

templates/login.html
{% extends "base.html" %} {% block content %}
      {% if form.errors %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        Your username and password didn't match. Please try again.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endif %} {% if next %} {% if user.is_authenticated %}
      <p>
        Your account doesn't have access to this page. To proceed, please login
        with an account that has access.
      </p>
      {% else %}
      <p>Please login to see this page.</p>
      {% endif %} {% endif %} {{ mesagge }}
      <form method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        <div class="row">
            {% for field in form %}
            <div class="col-8 mb-4">
                {{ field.label_tag }}
                {{ field }}
            </div>
            {% endfor %}
        </div>
        <input type="submit" class="btn btn-primary rounded" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
      </form>
{% endblock %}

templates/two_factor.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div {% if message.tags %}class="alert alert-{{ message.tags }} alert-dismissible fade show"{% endif %}
             role="alert">
            {{ message }}
            <button type="button" class="btn-close not-focusable" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
{% if expired %}
<a href="{% url 'accounts:generate_new_code' %}" class="btn btn-success">Generate new code</a>
{% endif %}
<h4>You have two minutes to enter the code</h4>
<p class="timer"></p>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-primary">Verify</button>
</form>
{% endblock %}